version: '3'

services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
    environment:
      - SE_GRID_MAX_SESSION=10   # Maximum sessions allowed on the grid
      - SE_GRID_BROWSER_TIMEOUT=120
      - SE_GRID_SESSION_TIMEOUT=180

  node-chrome:
    image: selenium/node-chrome
    deploy:
      replicas: 2  # Creates 2 Chrome nodes
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3   # Allow 3 sessions per node
      - SE_NODE_MAX_SESSIONS=3    # Total sessions that can run
      - SE_VNC_NO_PASSWORD=1      # No password for VNC access
    shm_size: '2g'  # Prevents tab crashes due to memory issues
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox
    deploy:
      replicas: 2  # Creates 2 Firefox nodes
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
      - SE_VNC_NO_PASSWORD=1
    shm_size: '2g'
    networks:
      - grid

  node-edge:
    image: selenium/node-edge
    deploy:
      replicas: 2  # Creates 2 Edge nodes
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
      - SE_VNC_NO_PASSWORD=1
    shm_size: '2g'
    networks:
      - grid  

networks:
  grid:
    driver: bridge
